#ifndef _MACROS_H_
#define _MACROS_H_

//Function return values
#define RETURN_OK 0
#define RETURN_ERROR_NEW_NODE_ALLOCATION_FAILED -1
#define RETURN_ERROR_ELEMENT_NOT_FOUND -2
#define RETURN_ERROR_ELEMENT_NOT_IN_RANGE -3
#define RETURN_ERROR_MEMORY_ALLOCATION_CODE -4
#define RETURN_ERROR_MEMORY_ALLOCATION_FAILED NULL

#define TRUE 1
#define FALSE 2

#define BUFFER_SIZE 256;

#endif
